export const CONSTANT = {
  PRODUCT_CATEGORIES: [
    "All",
    "Electronics",
    "Clothing & Apparel",
    "Home & Kitchen",
    "Beauty & Personal Care",
    "Sports & Outdoors",
    "Toys & Games",
    "Books & Stationery",
    "Health & Wellness",
    "Automotive",
    "Pet Supplies",
    "Grocery & Food",
    "Jewelry & Accessories",
    "Furniture",
    "Baby & Kids",
    "Office Supplies",
    "Software & Apps",
    "Arts & Crafts",
    "Travel & Luggage",
    "Music & Instruments",
    "Gardening & Outdoor Living",
  ],

  NATIVE_LANGUAGES: [
    { code: "en", name: "English", nativeName: "English" },
    { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
    { code: "bn", name: "Bengali", nativeName: "বাংলা" },
    { code: "te", name: "Telugu", nativeName: "తెలుగు" },
    { code: "mr", name: "Marathi", nativeName: "मराठी" },
    { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
    { code: "ur", name: "Urdu", nativeName: "اردو" },
    { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
    { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
    { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ" },
    { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
    { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
    { code: "as", name: "Assamese", nativeName: "অসমীয়া" },
    { code: "mai", name: "Maithili", nativeName: "मैथिली" },
    { code: "sat", name: "Santali", nativeName: "ᱥᱟᱱᱛᱟᱲᱤ" },
    { code: "ks", name: "Kashmiri", nativeName: "کٲشُر" },
    { code: "ne", name: "Nepali", nativeName: "नेपाली" },
    { code: "sd", name: "Sindhi", nativeName: "सिन्धी" },
    { code: "kok", name: "Konkani", nativeName: "कोंकणी" },
    { code: "doi", name: "Dogri", nativeName: "डोगरी" },
    { code: "mni", name: "Manipuri", nativeName: "মৈতৈলোন্" },
  ],
  SELECTION_HEADER_OPTIONS: [
    "All",
    "Fresh",
    "MX Player",
    "Sell",
    "Bestsellers",
    "Today's Deals",
    "Prime",
    "Mobiles",
    "Customer Service",
    "New Releases",
    "Electronics",
    "Fashion",
    "Amazon Pay",
    "Home & Kitchen",
    "Computers",
    "Books",
    "Car & Motorbike",
  ],
};